version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=studentdb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

  server:
    restart: on-failure
    build: .
    image: server
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/studentdb?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

networks:
  springmysql-net:
